### ISSUE TITLE
Details sending

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Shuman-Site#1]
When you click 'send details' after filling name and phone number the screen just go dark and there is no verification for sending the details.

**Comment by MeanEYE** [comment]
We'll check!

**Comment by iliyaM** [comment]
true

**Comment by MeanEYE** [comment]
@iliyaM true what?

**Comment by iliyaM** [comment]
true. this issue is happening

**Comment by talovdat** [comment]
I can see it got fixed.. Can i close the issue?

**Comment by MeanEYE** [comment]
Yes. Even though @iliyaM is suppose to do that.

**Comment by iliyaM** [comment]
No idea if its working or not. did change anything regarding that sits contact form just  changed style.
if its works then closing.
