### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Shuman-Site#3]
That happend after i clicked the video window. 

![image](https://cloud.githubusercontent.com/assets/26923359/25705555/56837614-30e6-11e7-9efb-591ffb00d6b2.png)

**Comment by MeanEYE** [comment]
This one is on me. I changed URL structure from old one to new one and probably missed ID or something for video.

**Comment by talovdat** [comment]
Is there a chance to play the video when clicking, at the same page.
It opens a new window with the video.
